#!/usr/bin/env bash
# ==============================================================================
# VALIDATE MODULE - Check module prerequisites before deployment
# ==============================================================================
# Description: Validates networks, secrets, env, and stack.yml for a module
# Author: Matt Barham
# Created: 2026-02-12
# Modified: 2026-02-12
# Version: 1.1.0
# ==============================================================================
# Usage: validate_module.sh MODULE_NAME [--post-env]
# ==============================================================================

set -euo pipefail
IFS=$'\n\t'

SPOKE_DIR="${SPOKE_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
MODULES_DIR="${SPOKE_DIR}/modules"
MODULES_YML="${SPOKE_DIR}/modules.yml"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

MODULE="${1:-}"
POST_ENV="${2:-}"

if [[ -z "${MODULE}" ]]; then
    printf "${RED}ERROR: Module name required${NC}\n" >&2
    printf "${YELLOW}Usage: %s MODULE_NAME [--post-env]${NC}\n" "$0" >&2
    exit 1
fi

MODULE_DIR="${MODULES_DIR}/${MODULE}"
COMPOSE_FILE="${MODULE_DIR}/docker-compose.yml"
ERRORS=0

printf "${BLUE}Validating module: %s${NC}\n" "${MODULE}"

# Check module directory exists
if [[ ! -d "${MODULE_DIR}" ]]; then
    printf "${RED}  FAIL: Module directory not found: %s${NC}\n" "${MODULE_DIR}" >&2
    printf "${YELLOW}  Run: make module-sync MODULE=%s${NC}\n" "${MODULE}" >&2
    exit 1
fi

# Check docker-compose.yml exists
if [[ ! -f "${MODULE_DIR}/docker-compose.yml" ]]; then
    printf "${RED}  FAIL: docker-compose.yml not found${NC}\n" >&2
    ERRORS=$((ERRORS + 1))
fi

# Check .env exists (should be generated by generate_module_env.sh)
if [[ ! -f "${MODULE_DIR}/.env" ]]; then
    printf "${YELLOW}  WARN: .env not found (will be generated during deploy)${NC}\n"
fi

# Check stack.yml if it exists (optional but recommended)
STACK_YML="${MODULE_DIR}/stack.yml"
if [[ -f "${STACK_YML}" ]]; then
    if ! command -v yq &>/dev/null; then
        printf "${YELLOW}  WARN: yq not installed, skipping stack.yml validation${NC}\n"
    else
        printf "${BLUE}  Checking stack.yml requirements...${NC}\n"

        # Check required networks exist
        # When .env is present, resolve actual network names from compose config
        # (handles env var overrides like PROXY_NETWORK=troxy for generic "proxy")
        if [[ -f "${MODULE_DIR}/.env" && -f "${COMPOSE_FILE}" ]]; then
            resolved_config=$(docker compose -f "${COMPOSE_FILE}" --env-file "${MODULE_DIR}/.env" config 2>/dev/null) || true
            if [[ -n "${resolved_config}" ]]; then
                external_networks=$(printf '%s\n' "${resolved_config}" | awk '
                    /^networks:/ { in_nets=1; net_name=""; is_ext=0; next }
                    in_nets && /^[^ ]/ {
                        if (net_name && is_ext) print net_name
                        in_nets=0
                    }
                    in_nets && /^  [a-zA-Z]/ {
                        if (net_name && is_ext) print net_name
                        net_name=""; is_ext=0
                    }
                    in_nets && /^    name:/ { net_name=$2 }
                    in_nets && /external: true/ { is_ext=1 }
                    END { if (in_nets && net_name && is_ext) print net_name }
                ')
                for network in ${external_networks}; do
                    if docker network inspect "${network}" &>/dev/null; then
                        printf "${GREEN}    Network %s: exists${NC}\n" "${network}"
                    else
                        printf "${RED}    Network %s: MISSING${NC}\n" "${network}" >&2
                        ERRORS=$((ERRORS + 1))
                    fi
                done
            fi
        else
            required_networks=$(yq -r '.requires.networks[]?.name // empty' "${STACK_YML}" 2>/dev/null)
            for network in ${required_networks}; do
                if docker network inspect "${network}" &>/dev/null; then
                    printf "${GREEN}    Network %s: exists${NC}\n" "${network}"
                else
                    printf "${RED}    Network %s: MISSING${NC}\n" "${network}" >&2
                    ERRORS=$((ERRORS + 1))
                fi
            done
        fi

        # Check required secrets exist
        required_secrets=$(yq -r '.secrets[]? | select(.required == true) | .name' "${STACK_YML}" 2>/dev/null)
        for secret in ${required_secrets}; do
            # Check if secret is mapped in modules.yml
            secret_path=$(yq -r ".modules.${MODULE}.secrets_map.${secret} // empty" "${MODULES_YML}" 2>/dev/null)
            if [[ -n "${secret_path}" ]]; then
                full_path="${SPOKE_DIR}/${secret_path}"
                if [[ -f "${full_path}" ]]; then
                    printf "${GREEN}    Secret %s: found${NC}\n" "${secret}"
                else
                    printf "${RED}    Secret %s: mapped but file missing (%s)${NC}\n" "${secret}" "${full_path}" >&2
                    ERRORS=$((ERRORS + 1))
                fi
            else
                printf "${YELLOW}    Secret %s: not mapped in modules.yml${NC}\n" "${secret}"
            fi
        done

        # Check required hub services are running
        hub_services=$(yq -r '.requires.hub_services[]? // empty' "${STACK_YML}" 2>/dev/null)
        for svc in ${hub_services}; do
            if docker ps --format '{{.Names}}' | grep -q "^${svc}$"; then
                printf "${GREEN}    Hub service %s: running${NC}\n" "${svc}"
            else
                printf "${RED}    Hub service %s: NOT running${NC}\n" "${svc}" >&2
                ERRORS=$((ERRORS + 1))
            fi
        done
    fi
else
    printf "${YELLOW}  INFO: No stack.yml found (optional)${NC}\n"
fi

# Validate docker-compose.yml syntax
if [[ -f "${COMPOSE_FILE}" ]]; then
    if [[ "${POST_ENV}" == "--post-env" ]]; then
        # Post-env: .env exists, so compose config should fully resolve
        printf "${BLUE}  Validating compose config (post-env)...${NC}\n"
        compose_errors=$(docker compose -f "${COMPOSE_FILE}" --env-file "${MODULE_DIR}/.env" config --quiet 2>&1) || {
            printf "${RED}  FAIL: docker-compose.yml config errors after env generation:${NC}\n" >&2
            printf "${RED}    %s${NC}\n" "${compose_errors}" >&2
            ERRORS=$((ERRORS + 1))
        }
        if [[ ${ERRORS} -eq 0 ]]; then
            printf "${GREEN}  docker-compose.yml config: valid${NC}\n"
        fi
    else
        # Pre-env: failures are expected (unresolved vars)
        if docker compose -f "${COMPOSE_FILE}" config --quiet 2>/dev/null; then
            printf "${GREEN}  docker-compose.yml syntax: valid${NC}\n"
        else
            printf "${YELLOW}  docker-compose.yml syntax: may have unresolved variables (normal before env gen)${NC}\n"
        fi
    fi
fi

# --- Post-env checks (only run with --post-env flag) ---
if [[ "${POST_ENV}" == "--post-env" && -f "${COMPOSE_FILE}" && -f "${MODULE_DIR}/.env" ]]; then

    # Check 1: Compose secrets file validation
    printf "${BLUE}  Checking compose secrets files...${NC}\n"
    compose_config=$(docker compose -f "${COMPOSE_FILE}" --env-file "${MODULE_DIR}/.env" config 2>/dev/null) || true
    if [[ -n "${compose_config}" ]]; then
        # Parse top-level secrets block for file: paths from resolved config
        secret_files=$(printf '%s\n' "${compose_config}" | sed -n '/^secrets:/,/^[^ ]/p' | grep 'file:' | awk '{print $2}' || true)
        for secret_file in ${secret_files}; do
            if [[ ! -f "${secret_file}" ]]; then
                printf "${RED}    Secret file missing: %s${NC}\n" "${secret_file}" >&2
                ERRORS=$((ERRORS + 1))
            else
                printf "${GREEN}    Secret file found: %s${NC}\n" "${secret_file}"
            fi
        done
    fi

    # Check 2: Compose profiles detection
    if grep -q 'profiles:' "${COMPOSE_FILE}" 2>/dev/null; then
        if grep -q '^COMPOSE_PROFILES=' "${MODULE_DIR}/.env" 2>/dev/null; then
            printf "${GREEN}  Compose profiles: COMPOSE_PROFILES is set${NC}\n"
        else
            printf "${YELLOW}  WARN: Compose file uses profiles: but COMPOSE_PROFILES not set in .env${NC}\n"
            printf "${YELLOW}    Services behind profiles will not start. Set COMPOSE_PROFILES in modules.yml env_overrides.${NC}\n"
        fi
    fi
fi

if [[ ${ERRORS} -gt 0 ]]; then
    printf "${RED}Validation failed with %d error(s)${NC}\n" "${ERRORS}" >&2
    exit 1
fi

printf "${GREEN}Module %s validated successfully${NC}\n" "${MODULE}"
